export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_LIST_FOLLOWING_REQUEST = 'POST_LIST_FOLLOWING_REQUEST';
export const POST_LIST_FOLLOWING_SUCCESS = 'POST_LIST_FOLLOWING_SUCCESS';
export const POST_LIST_FOLLOWING_FAIL = 'POST_LIST_FOLLOWING_FAIL';